### ISSUE TITLE
ROS can not find pretrained weights

### ISSUE THREAD

**Issue by nullket** [maudzung/SFA3D#13]
**Problem:**
Running the Nodes causes it to stop immediately stating that it can not find the file `fpn_resnet_18_epoch_300.pth`

**Solution:**

In [rosInference.py L119](https://github.com/maudzung/SFA3D/blob/master/ros/src/super_fast_object_detection/src/rosInference.py#L119) it tries to load the weights:

```python
package_path = rospack.get_path('super_fast_object_detection')
.....
configs.pretrained_path = package_path + '/checkpoints/fpn_resnet_18/fpn_resnet_18_epoch_300.pth'
```

But those are not contained in `package_path` which is `/some_folders/some_more_folders/SFA3D/ros/srcsuper_fast_object_detection/`. The weights are in the folder `/checkpoints` in the main root of this git. 

A not workaround would be:
```python
configs.pretrained_path = package_path + '/../../../checkpoints/fpn_resnet_18/fpn_resnet_18_epoch_300.pth'
```

Otherwise one could rethinking the whole structure. Maybe another ros repo should be opend where this repo is included as a submodule. This would also have some benefits like version control: The ros maintainer can state the to be used commit from the SFA3D main repo. If SFA3D maintainer updates SFA3D - maybe with with breaking changes - it would not break the ros node.

**Comment by maudzung** [comment]
@nullket 
Can you make a pull request on the issue? We will check and merge the PR.

Hi @AhmedARadwan 
Do you have ideas on the issue?

**Comment by AhmedARadwan** [comment]
Sure @maudzung. The proposed solution by @nullket will work.
Thanks @nullket for your help regarding this issue and I recommend you to make a pull request with the solution.

**Comment by nullket** [comment]
I can surely do this, but I can not test anything and therefore guarantee that it is working (okay super small change, I know) as the whole python 2/3 situation is still not clear, see Issue #11
