### ISSUE TITLE
What part can I refer to to detect continuously? 

### ISSUE THREAD

**Issue by FFudi** [maudzung/SFA3D#14]
The object disappears from the front and rear of the vehicle through the image and is detected again. What part can I refer to to detect continuously? Is the point cloud divided into the front and the rear to be detected? Thank you for providing great work.

**Comment by maudzung** [comment]
It's because of the KITTI dataset, they don't label objects that are not in the images. You can apply a simple tracking algorithm to keep objects' predicted label
