### ISSUE TITLE
False Object detection when running on autoware ROSbags

### ISSUE THREAD

**Issue by arjunskumar** [maudzung/SFA3D#19]
Used `wget https://autoware-ai.s3.us-east-2.amazonaws.com/sample_moriyama_150324.tar.gz` ROSbag file,
but many times false objects were detected. 

Could you please share a sample data-set to validate the ROS inference node?

**Comment by maudzung** [comment]
Hi @arjunskumar 
I have no ideas on it. Can you please contact to @AhmedARadwan for the ROS implementation?

**Comment by arjunskumar** [comment]
@AhmedARadwan Could you share the ROS bag file?
