### ISSUE TITLE
High Positive False Issue

### ISSUE THREAD

**Issue by zmin666666** [maudzung/SFA3D#23]
Dear @maudzung 

Thanks for your great work! We have trained SFA3D in the Waymo dataset. It seems great but still a problem. The False positive is common. Like in this picture, the bounding box is shown in a place without a car even when I set the thresh as 0.4. May you give us some tips to improve the result? Thanks

![Screenshot from 2020-12-19 13-51-29](https://user-images.githubusercontent.com/35618385/102697219-2dc22c80-4202-11eb-8334-ae9ff9fc52b1.png)

Zhimin Chen

**Comment by maudzung** [comment]
Great to see your work on it. I think you can set a bigger weight for the center loss component to reduce the false positive cases.
How about its performance on Waymo? Did you evaluate?

**Comment by zmin666666** [comment]
![Screenshot from 2020-12-23 12-01-09](https://user-images.githubusercontent.com/35618385/103020564-9e28c080-4516-11eb-99ef-7f1821d8cee7.png)
Thanks for your suggestion! This is the eval result in one Waymo data sequence (200 lidar bins). I do not know why easy, medium, and hard res are the same. Besides, I also try to use resnet34 and resnet50 as a backbone but the hm_loss can't converge. Have you tried to use resnet34 or 50 and how about the result? Thanks.

Zhimin Chen

**Comment by maudzung** [comment]
I only trained the resnet18-based model. 
To reduce false positive cases, you can try to increase 'peak_thresh' value. By default, its value has been set to 0.2.

**Comment by SofianeB-03** [comment]
Hello @Zhimin-C , I see that you have evaluated SFA3D on Waymo dataset. I want to evaluate on Waymo too  but I did not succeed. Could you tell me how did you evaluate it please? It will be very helpful for myself.
Thank you very much.

**Comment by SofianeB-03** [comment]
@Zhimin-C, if you could share me your pre-trained weights of SFA3D on Waymo that would be really super nice (I spent a lot of time trying to do this).
Thank you a lot!
