### ISSUE TITLE
RuntimeError while training FPN-Resnet18/34/50

### ISSUE THREAD

**Issue by YoushaaMurhij** [maudzung/SFA3D#25]
I got this error while trying to train fpn-resnet18/34/50 model on kitti.
It seems that  out_layer3 outputs `torch.Size([16, 256, 39, 39])` while up_level1 outputs `torch.Size([16, 512, 40, 40])`. Please can you suggest how to get rid of this error?  
```bash
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    main()
  File "train.py", line 67, in main
    main_worker(configs.gpu_idx, configs)
  File "train.py", line 161, in main_worker
    train_one_epoch(train_dataloader, model, optimizer, lr_scheduler, epoch, configs, logger, tb_writer)
  File "train.py", line 211, in train_one_epoch
    outputs = model(imgs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/docker_sfa3d/SFA3D/sfa/models/fpn_resnet.py", line 181, in forward
    concat_level1 = torch.cat((up_level1, out_layer3), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 39 and 40 (The offending index is 0)

```

**Comment by maudzung** [comment]
How about the input size?

**Comment by YoushaaMurhij** [comment]
The input is 609, 609

**Comment by maudzung** [comment]
It should be 608x608x3

**Comment by YoushaaMurhij** [comment]
I tried that before. It throughs this error:
```bash
File "/home/docker_sfa3d/SFA3D/sfa/data_process/kitti_bev_utils.py", line 37, in makeBEVMap
    IHD_Map[0, np.int_(PointCloud_top[:, 0]), np.int_(PointCloud_top[:, 1])] = PointCloud_top[:, 3]
IndexError: index 608 is out of bounds for axis 2 with size 608
```

**Comment by maudzung** [comment]
Did you get the latest code from the repo?

**Comment by YoushaaMurhij** [comment]
Yes, sure

**Comment by maudzung** [comment]
I think you didn't. Can you execute git pull and run again

**Comment by YoushaaMurhij** [comment]
`Already up to date.`
When I change the input size in kitti config to 609, 609. I get the first error again

**Comment by maudzung** [comment]
Hi @YoushaaMurhij 
Of course, the input size should be `608x608x3`.

How about the error? Did it disappear?
```
File "/home/docker_sfa3d/SFA3D/sfa/data_process/kitti_bev_utils.py", line 37, in makeBEVMap
    IHD_Map[0, np.int_(PointCloud_top[:, 0]), np.int_(PointCloud_top[:, 1])] = PointCloud_top[:, 3]
IndexError: index 608 is out of bounds for axis 2 with size 608
```

**Comment by YoushaaMurhij** [comment]
No, it didn't.

**Comment by maudzung** [comment]
Really weird. What did you execute?

**Comment by maudzung** [comment]
Anh please give me your git log

**Comment by YoushaaMurhij** [comment]
Here is git [log](https://docs.google.com/document/d/178TQnSCWhbx6-aIoDxXge9GM5359jRwBv8x_lRI-WjU/edit?usp=sharing): 
I excuted : `python train.py --gpu_idx 0`
Thank you for your replies and will to help :)

**Comment by maudzung** [comment]
![4E238028-8B1A-4445-AD57-B050D8C2D256](https://user-images.githubusercontent.com/15675550/104021910-e75d5d80-5202-11eb-87ab-b713b86ab6d4.jpeg)

**Comment by maudzung** [comment]
You can `git pull` or `git reset --hard 18d1d37c33dd46980eec56d62ec76c50a43b06bc `
