### ISSUE TITLE
Làm thế nào để tạo Custom dataset?

### ISSUE THREAD

**Issue by tranducanhbk** [maudzung/SFA3D#26]
Hi Dũng,
Mình muốn train với tập dữ liệu tự tạo
Làm thế nào để tạo các file dữ liệu bên dưới nhỉ:  
Velodyne point clouds 
Training labels of object data set 
Camera calibration matrices of object data set 
Left color images of object data set (12 GB)  

Cám ơn

**Comment by maudzung** [comment]
Hi @tranducanhbk 

Minh dung KITTI dataset, ban tham khao thong tin ve sensor setup [tai day](http://www.cvlibs.net/datasets/kitti/setup.php) nhe
