### ISSUE TITLE
How you are doing data augmentation?

### ISSUE THREAD

**Issue by Suri12990** [maudzung/SFA3D#30]
Hi Maudzung,

Thank you for your great work. But I just need to know how you are doing data augmentation and where? 
Could you please give me the hyperlink to data augmentation in your implementation?

I tried to find data augmentation, but I could not make it.

Thanks in advance

**Comment by maudzung** [comment]
It was applied [here](https://github.com/maudzung/SFA3D/blob/5f042b9d194b63d47d740c42ad04243b02c2c26a/sfa/data_process/kitti_dataset.py#L95). For more information, please take a look at [this file](https://github.com/maudzung/SFA3D/blob/master/sfa/data_process/transformation.py)
