### ISSUE TITLE
How long it will take to reimplement this code in tensorflow?

### ISSUE THREAD

**Issue by mariya12290** [maudzung/SFA3D#31]
Hey maudzung,

I am thinking to re implement your work in tensorflow. Could you please explain how long it will take if I start now?

I have limited time to do so. that is the reason.

Thanks in advance.

**Comment by maudzung** [comment]
Hi @mariya12290 
I think it's quite easy to re-implement this Pytorch work in `tf2`.
First, you need to build the model, create the data loader using tf2, then write the training and testing scripts for the task. That's all :-)
