### ISSUE TITLE
Add the  pointpillar feature network instead of the human made picture

### ISSUE THREAD

**Issue by wangx1996** [maudzung/SFA3D#32]
Hello, have you ever tried to add the  pointpillar feature network instead of the human made picture of pointcloud? And how to choose the number of the batchsize and the epoch when you training this work? I would  appreciate that if you can reply on me.

**Comment by maudzung** [comment]
HI @wangx1996 

The `PointPillar` approach is worth trying, but I haven't done experiments using the approach.

**Comment by wangx1996** [comment]
HI @maudzung 
In these days, I tried to add the pointpillar head to make an anchor free detecion method, and I publish on my github https://github.com/wangx1996/CenterPillarNet
But it still has a lot of problems, the AP looks not so good, and  I don't know how to improve this.

**Comment by maudzung** [comment]
Thanks @wangx1996 
I should close this issue. I'll update if I done the pillar-based implementation
