### ISSUE TITLE
Reference and performance

### ISSUE THREAD

**Issue by SofianeB-03** [maudzung/SFA3D#33]
Hello, thank you for your great work. I’m an intern who work on perception 3D for autonomous vehicles and I would like to use your project Super-Fast-Accurate-3D-Object-Detection-PyTorch. I have a suggestion : Is there a specific reference on this method and also is there comparison ((AP metric and inference time) with others methods on dataset like KITTI ?

Thank you.

**Comment by maudzung** [comment]
You can refer to [this PR](https://github.com/maudzung/SFA3D/pull/47)
