### ISSUE TITLE
How can I use a Lidar for live feed to the network?

### ISSUE THREAD

**Issue by husnejahan** [maudzung/SFA3D#35]
I want to use just a Lidar like Ydlidar to get live detection from the point cloud.
Can You guide me?

**Comment by maudzung** [comment]
Hi @husnejahan 
Thanks for your interest in my work.

The steps are:
- Extract your data as same as the KITTI format, please refer to the KITTI official website.
- Change the configuration of the dataset [here](https://github.com/maudzung/SFA3D/blob/master/sfa/config/kitti_config.py)
- Refer to the [demo_dataset.py](https://github.com/maudzung/SFA3D/blob/master/sfa/data_process/demo_dataset.py) to see how to create the dataset for the task
- Refer [demo_2_sides.py](https://github.com/maudzung/SFA3D/blob/master/sfa/demo_2_sides.py) to see how the working flow is

**Comment by yzfneo** [comment]
@maudzung Thank you for you great work! Based on this topic, just curious that if the detection is made on ROS platform, can we just use/modify [this script](https://github.com/maudzung/SFA3D/blob/ea0222c1b35489dc35d8452c989c4b014e20e0da/ros/src/super_fast_object_detection/src/rosInference.py) for point cloud topic subscriptions, and achieve similar detection as Kitti dataset? (Do we need any additional data-processing for live lidar data?) Thanks in advance.

**Comment by urbansound8K** [comment]
how can I make that from a data lidar itself? I mean a real-time instead of getting a saved data only
