### ISSUE TITLE
Can you provide a script evaluate.py please ?

### ISSUE THREAD

**Issue by SofianeB-03** [maudzung/SFA3D#37]
Hello, thanks you for your great work! It's very interesting. I would like to evaluate this model (AP per classe and mAP) like ComplexYolov4. Can you provide a script evaluate.py please?

thank you.

**Comment by bilgecanpullinen** [comment]
Hi @maudzung , I am interested in your work as well and it would be amazing if you could share the evaluation file.
Thank you

**Comment by maudzung** [comment]
You can refer to [this PR](https://github.com/maudzung/SFA3D/pull/47)
