### ISSUE TITLE
bev not good, suggest one

### ISSUE THREAD

**Issue by shen1994** [maudzung/SFA3D#40]
cpoint_cloud = np.copy(point_cloud)
	
	rgb_map = np.zeros((3, cnf.BEV_HEIGHT, cnf.BEV_WIDTH), dtype=np.float32)
	rgb_map_cnt = np.zeros((cnf.BEV_HEIGHT, cnf.BEV_WIDTH), dtype=np.int)
	max_height = float(cnf.boundary['maxZ'] - cnf.boundary['minZ'])
	for point in cpoint_cloud:
		x = np.floor(point[0] / cnf.DISCRETIZATION_X) + np.int_(cnf.OFFSET_X)
		y = np.floor(point[1] / cnf.DISCRETIZATION_Y) + np.int_(cnf.OFFSET_Y)
		x = int(x)
		y = int(y)
		if x >= cnf.BEV_HEIGHT or y >= cnf.BEV_WIDTH:
			continue
		rgb_map[0, x, y] += point[3] / 255.0
		rgb_map[1, x, y] += (point[2] - cnf.boundary['minZ']) / max_height
		rgb_map_cnt[x, y] += 1

	for point in cpoint_cloud:
		x = np.floor(point[0] / cnf.DISCRETIZATION_X) + np.int_(cnf.OFFSET_X)
		y = np.floor(point[1] / cnf.DISCRETIZATION_Y) + np.int_(cnf.OFFSET_Y)
		x = int(x)
		y = int(y)
		if x >= cnf.BEV_HEIGHT or y >= cnf.BEV_WIDTH:
			continue
		if 0 == rgb_map[2, x, y]:
			rgb_map[0, x, y] /= rgb_map_cnt[x, y]
			rgb_map[1, x, y] /= rgb_map_cnt[x, y]
			rgb_map[2, x, y] = np.minimum(1.0, np.log(rgb_map_cnt[x, y]+1) / np.log(cnf.unique_max))

**Comment by shen1994** [comment]
BirdViewMap::BirdViewMap()
{
	params_ = std::make_shared<Config>();

	cudaMalloc((void**)&cnt_gpu_, params_->bev_size_ * sizeof(int));
	cudaMalloc((void**)&bev_gpu_, params_->bev_size_ * 3 * sizeof(float));
}

BirdViewMap::~BirdViewMap()
{
	cudaFree(cnt_gpu_);
	cudaFree(bev_gpu_);
}

__global__ void cuda_range_filter(float* pc, float min_x, float max_x,
	float min_y, float max_y, float min_z, float max_z, int points_num)
{
	int id = blockDim.x * blockIdx.x + threadIdx.x;
	if(id >= points_num)
	{
		return ;
	}

	if(pc[id*4] <= min_x || pc[id*4] >= max_x
		|| pc[id*4+1] <= min_y || pc[id*4+1] >= max_y
		|| pc[id*4+2] <= min_z || pc[id*4+2] >= max_z)
	{
		pc[id*4] = 0;
		pc[id*4+1] = 0;
		pc[id*4+2] = 0;
		pc[id*4+3] = 0;
	}
}

__global__ void cuda_generate_info(float* pc, 
	float xgrid, float ygrid, float xoffset, float yoffset, float z_min, float z_size,
	float* bev_map, int bev_height, int bev_width, int bev_size, int* cnt, int points_num)
{
	int id = blockDim.x * blockIdx.x + threadIdx.x;
	if(id >= points_num)
	{
		return ;
	}
	if(0 == pc[id * 4] && 0 == pc[id * 4 + 1] 
		&& 0 == pc[id*4+2] && 0 == pc[id*4+3])
	{
		return ;
	}

	int x = __float2int_rd(floorf(pc[id * 4] / xgrid) + xoffset);
	int y = __float2int_rd(floorf(pc[id * 4 + 1] / ygrid) + yoffset);
	if(x >= bev_height || y >= bev_width)
	{
		return ;
	}

	int map_id = x * bev_width + y;

	float intensity = (pc[id * 4 + 3] / 255.0f);
	float zcoor = (pc[id * 4 + 2] - z_min) / z_size;

	atomicAdd(bev_map+map_id, intensity);
	atomicAdd(bev_map+bev_size+map_id, zcoor);
	atomicAdd(cnt+map_id, (int)1);
}

__global__ void cuda_generate_bev(float* bev_map, 
	int* cnt, float max_unique, int bev_size)
{
	int id = blockDim.x * blockIdx.x + threadIdx.x;
	if(id >= bev_size)
	{
		return ;
	}

	int max_cnt = max(1, cnt[id]);
	float zcoor = bev_map[id+bev_size] / (float)max_cnt;
	float intensity = bev_map[id] / (float)max_cnt;

	float rate = logf((float)cnt[id] + 1.0f) / logf(max_unique);
	float map_rate = min(1.0f, rate);

	bev_map[bev_size*2+id] = map_rate;
	bev_map[bev_size+id] = zcoor;
	bev_map[id] = intensity;
}

void BirdViewMap::make_bev_map(float* points_gpu, int points_num)
{
	cudaMemset(cnt_gpu_, 0, params_->bev_size_ * sizeof(int));
	cudaMemset(bev_gpu_, 0, params_->bev_size_ * 3 * sizeof(float));

	printf("%f, %f, %f, %f\n", params_->bound_grid_x_, params_->bound_grid_y_, 
		(float)params_->offset_x_, (float)params_->offset_y_);

	dim3 thread1d; dim3 block1d; thread1d.x = 1024;
	block1d.x = (points_num + thread1d.x - 1) / thread1d.x;
	cuda_range_filter<<<block1d, thread1d>>>(points_gpu, params_->bound_min_x_, params_->bound_max_x_,
		params_->bound_min_y_, params_->bound_max_y_, params_->bound_min_z_, params_->bound_max_z_, points_num);
	cudaDeviceSynchronize();

	cuda_generate_info<<<block1d, thread1d>>>(points_gpu, params_->bound_grid_x_, params_->bound_grid_y_, 
		(float)params_->offset_x_, (float)params_->offset_y_, params_->bound_min_z_, params_->bound_size_z_, 
		bev_gpu_, params_->bev_height_, params_->bev_width_, params_->bev_size_, cnt_gpu_, points_num);
	cudaDeviceSynchronize();

	block1d.x = (params_->bev_size_ + thread1d.x - 1) / thread1d.x;
	cuda_generate_bev<<<block1d, thread1d>>>(bev_gpu_, cnt_gpu_, (float)params_->max_unique_, params_->bev_size_);
	cudaDeviceSynchronize();
}

**Comment by vivi0604** [comment]
你好，我有两个问题向您请教：
1.这个改进可以提高精度吗？看代码没有太看懂，可以简单说一下思路吗？
2.第二部分代码是在用cuda加速第一部分吗？

**Comment by shen1994** [comment]
> 你好，我有两个问题向您请教：
> 1.这个改进可以提高精度吗？看代码没有太看懂，可以简单说一下思路吗？
> 2.第二部分代码是在用cuda加速第一部分吗？

yep, speed first one

**Comment by vivi0604** [comment]
请问您有遇到val_loss曲线先下降后上升的情况吗，如下图：
![image](https://user-images.githubusercontent.com/38038575/120978696-55ed1a00-c7a7-11eb-8c4a-b531752ded82.png)
我并没有改作者的代码，也没有改参数，可是训练出来的模型效果远远不如作者提供的预训练模型（用kitti数据集），请问您可以给我提供一些建议使它work吗?
