### ISSUE TITLE
i have found resnet50 has better performance than fpn_reset18/34

### ISSUE THREAD

**Issue by shen1994** [maudzung/SFA3D#41]
cause info from pointcloud has not space structure, so it's results not so good, anchor free's method maybe not useful

**Comment by vivi0604** [comment]
请问你用的是kitti数据集吗？我用自己的数据集测试，resnet50+fpn好像不如fpn_reset18/34效果好呢

**Comment by maudzung** [comment]
Hi @shen1994 
Thanks for your observation. I agree with your points. We always need to trade-off between accuracy and speed.
