### ISSUE TITLE
KeyError: 'optimizer' when resuming training from checkpoint

### ISSUE THREAD

**Issue by yukaryote** [maudzung/SFA3D#48]
I am trying to resume training from the checkpoint provided in the repo (fpn_resnet_18_epoch_300.pth), and when I run `python train.py --gpu_idx 0 --resume_path ../checkpoints/fpn_resnet_18/fpn_resnet_18_epoch_300.pth` I get this error:

`Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main()
  File "train.py", line 67, in main
    main_worker(configs.gpu_idx, configs)
  File "train.py", line 132, in main_worker
    optimizer.load_state_dict(utils_state_dict['optimizer'])
KeyError: 'optimizer'`

**Comment by maudzung** [comment]
Hi @yukaryote 
I saved weights & optimizer states in 2 files
