### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by mouawiya** [maudzung/SFA3D#49]
hello, i am currently always facing a cuda out of memory error when i run the train.py file, i looked though the internet it said that i needed to lower the batch size but i don't know how to dot that, there isn't like a clear batch size number or value i can decrease, so can you please help me.

**Comment by urbansound8K** [comment]
python train.py --gpu_idx 0 --batch_size 1

**Comment by maudzung** [comment]
Thanks @urbansound8K
