### ISSUE TITLE
how to get boundry parameters?

### ISSUE THREAD

**Issue by rajeshchiplogictech** [maudzung/SFA3D#54]
in kitti_config.py, there is paramter boundary and the values is boundary = {
    "minX": 0,
    "maxX": 50,
    "minY": -25,
    "maxY": 25,
    "minZ": -2.73,
    "maxZ": 1.27
}.

so my question is how i get this paramter values from my dataset. i have .las and .bin point cloud files only. also i dont have calib files. so can i used kitti calib files?

**Comment by maudzung** [comment]
Hi @rajeshchiplogictech 
Point clouds are stored in a NumPy array. You can easily get the min and max values of the data.
