### ISSUE TITLE
How to train the model for other classes and larger range

### ISSUE THREAD

**Issue by bhaskar-anand-iith** [maudzung/SFA3D#59]
Thank you for this code.

I am facing a problem while using ROS implementation of SFA3D on my data. The detected bounding box disappears after certain distance (say 40m). Also other classes like pedestrian, truck are not detected.

May I know how to train this model for larger distance (100m) and for other classes (pedestrain, truck Bus )

**Comment by maudzung** [comment]
Hi @bhaskar-anand-iith 
Sure, you can modify the config [here](https://github.com/maudzung/SFA3D/blob/master/sfa/config/kitti_config.py)
