### ISSUE TITLE
Update the ROS Nodes for newer versions of OpenCV

### ISSUE THREAD

**Issue by TheGodOfWar007** [maudzung/SFA3D#61]
Outdated enum variables are causing build failures with newer versions of OpenCV, especially the `CV_AA` and `CV_FILLED` markers in the `visualize_rects.h` header file from the `detected_objects_visualizer` package. Consider replacing them by the newer versions `cv::LINE_AA` and `cv::FILLED`. Please make the requisite changes in the other files as well. I will post if I come across similar bugs, but so far, the package was built successfully after replacing the above markers in the mentioned header file.

Note: I am using `ROS Noetic` with source built `OpenCV 4.x`.

**Comment by maudzung** [comment]
For ROS implementation, please contact @AhmedARadwan to get instructions. Many thanks
