### ISSUE TITLE
What are the camera calibration matrices used for in training?

### ISSUE THREAD

**Issue by sisaha9** [maudzung/SFA3D#65]
Can we make do without them?

**Comment by maudzung** [comment]
No, I used only lidar data to train the SFA3D model. Images were only used for output visualization.

**Comment by sisaha9** [comment]
Hi @maudzung . Thanks for the quick reply. We tested by removing the images (which worked) and the camera calibration matrices (which did not work). So it is being read in for the train script. Would you know why/which file I should look at to get rid of the dependency?
