### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by mouawiya** [maudzung/SFA3D#67]
can you please write a paper or a rapport on the method you used so we could follow the steps of the detection

**Comment by bhaskar-anand-iith** [comment]
Agreed.. At least a white paper will help to understand the model.
At present the technical details given is too short to understand the model

**Comment by maudzung** [comment]
I'm sorry. I only reported the technical details in [the note](https://github.com/maudzung/SFA3D/blob/master/Technical_details.md)
