### ISSUE TITLE
Can you tell me more about what 3D-Object-Detection Architecture that you have used and what part in this git? I am still not clear when reading your README file

### ISSUE THREAD

**Issue by leducnguyen21** [maudzung/SFA3D#69]

**Comment by maudzung** [comment]
Hi @leducnguyen21 
As I mentioned in the README.md file, I described the technical details in [this file](https://github.com/maudzung/SFA3D/blob/master/Technical_details.md)

**Comment by leducnguyen21** [comment]
Thank you for your response

Vào Th 6, 24 thg 6, 2022 vào lúc 12:52 Nguyen Mau Dzung <
***@***.***> đã viết:
