### ISSUE TITLE
Using my own data

### ISSUE THREAD

**Issue by Jae-Seung-Jeon** [maudzung/SFA3D#9]
**Hello, I want to create data using 3 Lidars and use your program. There are bin files and png files that I made.**

![Super2](https://user-images.githubusercontent.com/68648280/92309624-2627a080-efe2-11ea-98c1-d45e7cdb71ea.png)
![Super3](https://user-images.githubusercontent.com/68648280/92309629-2889fa80-efe2-11ea-8bc4-a326ed9c8580.png)

**But, how can I create a txt file to go into the Calib folder?**

![Super4](https://user-images.githubusercontent.com/68648280/92309818-a26eb380-efe3-11ea-837e-b92d9a6534e2.png)

**There are other github packages that calibrate Lidar and Camera.** 
**However, I cannot fully understand the details of 000000.txt,** 
**and I cannot calibrate because I cannot create my own txt file that plays the exact same role as the txt file in the Calib folder.**

**1. If you know the contents of 000000.txt, can you tell me?**
**2. Can I create a txt file with my camera and Lidars?**

**Comment by maudzung** [comment]
Hi @Jae-Seung-Jeon 
Of course, you can use the source code with your own data, but you need to manipulate the code. 
I'll guide you on it soon!

**Comment by Jae-Seung-Jeon** [comment]
Thank you very much @maudzung !! If possible, politely ask within a few days. I am using 3 VLP16. Thank you so much for the replies and feedback.

**Comment by nicholasguimaraes** [comment]
> Hi @Jae-Seung-Jeon
> Of course, you can use the source code with your own data, but you need to manipulate the code.
> I'll guide you on it soon!

Do we have a tutorial on how to train  the network on our own data yet?

**Comment by chyphen7** [comment]
How do we generate labels for each of our own data?   Thanks.
